In [1]:
import math
import numpy as np
from fractions import Fraction

In [2]:
def double_eca(P,a,b):
    x=P[0]
    y=P[1]
    z=P[2]
    X = Fraction(x,z)
    Y = Fraction(y,z)
    
    mu = Fraction((3*(X**2) + a),(2*Y))    
    Xd = (mu**2) - 2*X
    Yd = mu*(X - Xd) - Y
    theta = lcm(Xd.denominator, Yd.denominator)
    res=[theta*Xd, theta*Yd, theta]
    return([a.numerator for a in list(res)])

def sum_eca(P1,P2,a,b):
    X1 = Fraction(P1[0],P1[2])
    Y1 = Fraction(P1[1],P1[2])
    X2 = Fraction(P2[0],P2[2])
    Y2 = Fraction(P2[1],P2[2])
    mu = Fraction((Y2 - Y1),(X2 - X1))
    Xs = (mu**2) - X1 - X2
    Ys = mu*(X1 - Xs) - Y1
    theta = lcm(Xs.denominator, Ys.denominator)
    res = [theta*Xs, theta*Ys, theta]
    return([a.numerator for a in list(res)])

def lcm(a, b):
    return(abs(a*b) // math.gcd(a, b))

def f(A):
    res=[570*A[0] + 570*A[1] - 277*A[2], 
         1092*(A[0] - A[1]), 
         3*(6*A[0] + 6*A[1] - A[2])]
    return(res)

def f_inv(P):
    return([-3*P[0] + 3*P[1] + 277*P[2], 
                     -3*P[0] - 3*P[1] + 277*P[2], 
                     -36*P[0] + 1140*P[2]])

def banana(A):
    return(A[0]*(A[0] + A[2])*(A[0] + A[1]) + 
               A[1]*(A[2] + A[1])*(A[0] + A[1]) + 
               A[2]*(A[2] + A[1])*(A[2] + A[0]) - 
               4*(A[0] + A[1])*(A[1] + A[2])*(A[2] + A[0]))
    
def ec(P):
    return(Fraction(2370314,27)*(P[2]**3) - Fraction(11209,3)*(P[0]*(P[2]**2)) + (P[0]**3) - (P[1]**2)*P[2])

In [3]:
## Find one point

n=12
for a in np.arange(-n,n):
    for b in np.arange(-n,n):
        for c in np.arange(-n,n):
            A=np.array([a,b,c],dtype=int)
            if((banana(A)==0) and (a+b)!=0 and (b+c)!=0 and (a+c)!=0):
                print(A)


[-11  -9   5]
[-11  -4   1]
[-11   1  -4]
[-11   5  -9]
[ -9 -11   5]
[ -9   5 -11]
[-5  9 11]
[-5 11  9]
[ -4 -11   1]
[ -4   1 -11]
[-1  4 11]
[-1 11  4]
[  1 -11  -4]
[  1  -4 -11]
[ 4 -1 11]
[ 4 11 -1]
[  5 -11  -9]
[  5  -9 -11]
[ 9 -5 11]
[ 9 11 -5]
[11 -5  9]
[11 -1  4]
[11  4 -1]
[11  9 -5]


In [4]:
## define one point P on the elliptic curve
A = [1,-4,-11]
P=f(A)

print("A: " + str(A))
print("banana(A): " + str(banana(A)))
print("P=f(A): " + str(P))
print("elliptic curve(P): " + str(ec(P)))

A: [1, -4, -11]
banana(A): 0
P=f(A): [1337, 5460, -21]
elliptic curve(P): 0


In [32]:
## compute n * P
a = Fraction(-11209,3)
b = Fraction(2370314,27)

P_dict={}
P_dict[1]=P
P_dict[2]=double_eca(P_dict[1],a,b)

nmax=300
for i in np.arange(3,nmax):
    if i%2==1:
        P_dict[i] = sum_eca(P_dict[(i-1)//2],P_dict[((i-1)//2)+1],a,b)
    if i%2==0:
        P_dict[i] = double_eca(P_dict[i//2],a,b)

In [33]:
A_list = [f_inv(P) for P in list(P_dict.values())]
A_pos_list=[]
for A in A_list:
    if A[0]>0 and A[1]>0 and A[2]>0:
        print("="*50)
        print(A[0])
        print("="*10)
        print(A[1])
        print("="*10)
        print(A[2])
        A_pos_list.append(A)

331876186147169998444780304087029273429436819720747738966548237244735021706500211
1390291218978715497977561835179278537370978931026088885300239714084278818317501991
39362514101358275320751273421342511375348838023454522567592941940405811209948324
8790444378053931778556581817259350485782036948208565429931789202181056133423594441105493572533350308536735981793365302089094732619463681192753891297910026892438724896761005237912933721504797085335946025374516920334747669805741375171012088366289285635463241715368735442363152418638876890784
1348171706606506098705905523944234895834205707206225487797440150495186180509956177161676173486361152522097761949584437051597622159238666533260615715023514760993093552172415061466366538801741528441396539169854695219480877223192734481987981888930762722460063617827997101284157519060253330744
986740730991393122654219614384577867495326404083518750202233585557506665136905653897997785682342930890023446680244298794033362936630437830378303119152675594707153903072899649

In [31]:
len(A_pos_list)

3